### ISSUE TITLE
[Suggestion] Per game different gamble amounts

### ISSUE THREAD

**Issue by Greazi-Times** [aematsubara/Roulette#1]
A possibility to make it so you can change the gamble amount per table. So for example you can bet on table 1 up to 1.000 coins and on table 2 from 1.000 to 10.000

**Comment by Nokrato** [comment]
option for hide npc name, and change the skin using the command `/npc skin -url `

**Comment by Greazi-Times** [comment]
> option for hide npc name, and change the skin using the command `/npc skin -url `
> 
> 

You need to make a new suggestion

**Comment by aematsubara** [comment]
I'll start working on this one (yes I know, late af). I think a GUI can be added so the admin can select the desired chips to use

**Comment by aematsubara** [comment]
Done! Took 2 years but it's here
