### ISSUE TITLE
Bugs on 1.19

### ISSUE THREAD

**Issue by Nolex01** [aematsubara/Roulette#12]
%money% placeholder on map issue:
[Roulette] The line for the map "$29,988.30" contains invalid characters!

W and S not working for navigation.

**Comment by aematsubara** [comment]
For the first problem, can I see you config.yml?

For the second, what do you mean with navigation? When swaping chairs or when moving chips? Also, do you got any errors in console?

**Comment by MrNolex** [comment]
I am using the default config

When moving chips
(No errors just for the map)

and also new bug:
- Players cant bet on the same spot
(If someone already bet on red, no one else can)

**Comment by aematsubara** [comment]
Try with the latest release
