### ISSUE TITLE
Suggestion: option to sit for next round already :D

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#19]
It would be nice if player could stay in their seat if they started once

so they would automaticly join next round if they stay sitting on their seat..

Specialy when more players wanne do some rounds
it would be nice if all join (they sit)
and then could do round by round without needing to cklick the join hologramm aggain and may also take their seats..

**Comment by aematsubara** [comment]
A bit late, but let's work on this. I really like this suggestion, maybe that can be an option that can be toggle by right-clicking the NPC

**Comment by CloudeLecaw** [comment]
so a new game settting at can be choosen in the Option GUI of the table that is defined by clicking the NPC?

Great Idea :D

**Comment by aematsubara** [comment]
Added in the latest update!
