### ISSUE TITLE
Winning Chance is calcualted wrongly

### ISSUE THREAD

**Issue by CloudeLecaw** [aematsubara/Roulette#20]
well 26% is a wrong calcualtion...

1 / 38 = 0,026
1.00 = 100%
0,025 * 100,00 / 1,00 = 2,6
so 0,026 would be 2,6%.....

![Snag_2588287](https://user-images.githubusercontent.com/12080017/192063723-107d5745-7d34-410c-aedc-2d5efb06e3d4.png)

**Comment by aematsubara** [comment]
Fixed in latest release
