### ISSUE TITLE
[ERRORS] in console

### ISSUE THREAD

**Issue by DaDiGui** [aematsubara/Roulette#36]
The console is full of these errors although the ingame plugin works correctly.

`Plugins (33): LuckPerms, PlaceholderAPI, TargetPractice, TrueCompanies, Blackjack, ProtocolLib, Devotions, SkinsRestorer, Referral, NBTAPI, McEventCore, TradingCards, Vault, BitcoinReloaded, Windcuff, WorldEdit, AnimatedScoreboard, CookieClicker, DecentHolograms, WhackaMole, MineM-Invoices, QuickTax, CommandPanels, XConomy, WorldGuard, Roulette, Telecom, TAB, BlockStreet, WorldGuardEvents, MoneyPrinters, EvenMoreFish, ConditionalEvents`

log: https://mclo.gs/vLliHoE

**Comment by aematsubara** [comment]
Update to the latest release, this should be fixed!
